// This file is normally generated by `flutterfire configure`.
//
// For this coding test, it's included as a stub so the project compiles.
// Replace these placeholders by running:
//   flutterfire configure
// which will generate the correct options for your Firebase project.
//
// Docs: https://firebase.flutter.dev/docs/cli/

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJe5WJvS03EaQfWPOgOc2laHs5oUvxMII',
    appId: '1:918019570254:web:b0a3ee7c53a342ff2ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    authDomain: 'ecommerceapp-79423.firebaseapp.com',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    measurementId: 'G-GF99DKWS3Q',
  );

  // NOTE: All values below are placeholders.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05XaP5E12DTG452DBubj99Ks6fDl-A8Q',
    appId: '1:918019570254:android:b6181c83cfd88f652ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0WeafrJmIO4Kx2YakRTJUenRwc_6e690',
    appId: '1:918019570254:ios:a7139186192dbd9b2ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    androidClientId: '918019570254-g7eu5vlj9vfpa2sq3ciolq5239677q20.apps.googleusercontent.com',
    iosClientId: '918019570254-m84u93d3iljicieq47bgovoaj5m74b7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0WeafrJmIO4Kx2YakRTJUenRwc_6e690',
    appId: '1:918019570254:ios:a7139186192dbd9b2ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    androidClientId: '918019570254-g7eu5vlj9vfpa2sq3ciolq5239677q20.apps.googleusercontent.com',
    iosClientId: '918019570254-m84u93d3iljicieq47bgovoaj5m74b7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6n5tDcrmUk8v5VMOTszo5IeM2ouY6yTI',
    appId: '1:918019570254:web:97b5c40a27f060432ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    authDomain: 'ecommerceapp-79423.firebaseapp.com',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    measurementId: 'G-2YPVRH0GDX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}